version: "3"

services:
  app:
    build: . 
    image: lalitpatidar001/pet-adoption-backend:latest
    ports: 
      - 4000:4000
    environment:
       - PORT = ${PORT}
       - DB_URL = ${DB_URL}
       - JWT_SECRET_KEY = ${JWT_SECRET_KEY}
       - JWT_ISSUER = ${JWT_ISSUER}
       - JWT_AUDIENCE = ${JWT_AUDIENCE}
       - JWT_ALGORITHM = ${JWT_ALGORITHM}
       - JWT_EXPIRES_IN = ${JWT_EXPIRES_IN}
       - SESSION_SECRET = ${SESSION_SECRET}
       - OAUTH_SUCCESS_URL = ${OAUTH_SUCCESS_URL}
       - OAUTH_FAILURE_URL = ${OAUTH_FAILURE_URL}
       - GOOGLE_AUTH_CLIENT_ID = ${GOOGLE_AUTH_CLIENT_ID}
       - GOOGLE_AUTH_CLIENT_SECRET = ${GOOGLE_AUTH_CLIENT_SECRET}
       - GOOGLE_AUTH_CALLBACK_URL = ${GOOGLE_AUTH_CALLBACK_URL}
     



     